### ISSUE TITLE
Consolidate Simulators

### ISSUE THREAD

**Issue by Modularius** [STFC-ICD-Research-and-Design/supermusr-data-pipeline#105]
The run-simulator and simulator tool are to be amalgamated at some point in the future.
This should only happen when simulator has been improved to simulate a wide variety of trace and event patterns and has been fully tested.
Keeping run-simulator separate protects it from unforeseen errors that might occur whilst the simulator tool is being developed.

**Comment by DanNixon** [comment]
To be more clear, I think it should happen alongside the consolidation of the two existing simulators.

**Comment by DanNixon** [comment]
Another thing to address alongside this would be the ability to simulate multiple digitisers, i.e. being able to fake synchronisation by sending multiple unique frames with the same status packet.
