### ISSUE TITLE
Event aggregator fails when not using OpenTelemetry

### ISSUE THREAD

**Issue by DanNixon** [STFC-ICD-Research-and-Design/supermusr-data-pipeline#166]
@Modularius please could you review all the OpenTelemetry code and ensure things like this cannot happen.

```
thread 'main' panicked at digitiser-aggregator/src/frame/cache.rs:32:45:
called `Result::unwrap()` on an `Err` value: UninitialisedRead
```

Re #162

**Comment by Modularius** [comment]
Sorry, forgot to mention I'd encountered this earlier. It's fixed in the code I was working on in the catch up.
