### ISSUE TITLE
Aggregator may need to filter out external events

### ISSUE THREAD

**Issue by Modularius** [STFC-ICD-Research-and-Design/supermusr-data-pipeline#187]
Currently the aggregator accepts any valid dat_event message from the broker. It might be that the aggregator needs to filter out messages that were not generated by trace-to-events, or maybe another solution can be found (such as creating a dedicated topic for trace-to-event messages).

**Comment by DanNixon** [comment]
Not really sure what the issue is here, the topic that the aggregator listens to should only contain events for a single source so ingesting everything is the correct thing to do.

**Comment by Modularius** [comment]
HiFi was sending its own randomized DAT event messages which were interfering with the ones we created so I had to filter them out by checking the message key as a temporary fix.

I'll create a new topic on the broker specifically for our event messages however. It's something to be aware of in the future though, I think.

**Comment by DanNixon** [comment]
Yes, as I say, the digisers should not have been sending messages to the same event topic.
