### ISSUE TITLE
Nexus file timeseries should be shifted to start of run

### ISSUE THREAD

**Issue by Modularius** [STFC-ICD-Research-and-Design/supermusr-data-pipeline#206]
The offsets of selog entries and the event_time_zero fields should be from the start of the run rather than the time of the first incoming selog or data message.

**Comment by DanNixon** [comment]
It was confirmed by FA that neutron instruments that operate a multi period mode store data in a single event list.

So we shall do the same here.

This should be documented in the ADR for the NeXus format as part of #159.
