### ISSUE TITLE
Event formation mode: fixed-threshold-discriminator

### ISSUE THREAD

**Issue by Modularius** [STFC-ICD-Research-and-Design/supermusr-data-pipeline#266]
## Problem this feature will solve

The current fixed threshold discriminator does not record any meaningful pulse-height data.

## Description of solution

~~An additional mode in the event formation component: `fixed-threshold-discriminator-with-pulse-max` will record the pulse height as the maximum value of the trace between the event triggering and the discriminator rearming.~~

The event formation mode : `fixed-threshold-discriminator` will record the pulse height as the maximum value of the trace between the event triggering and the discriminator rearming.

**Comment by DanNixon** [comment]
Based on the meeting this was discussed in, I don't think this should be an additional mode, just the actual behaviour of the fixed threshold discriminator.
