### ISSUE TITLE
nexus-writer

### ISSUE THREAD

**Issue by DanNixon** [STFC-ICD-Research-and-Design/supermusr-data-pipeline#8]
Write a Mantid compatible NeXus file given detector, metadata and run boundary information via Kafka.

There are several kinds of message that can be received via Kafka (some may be on different topics):

- Run start/stop
- Detector data
- Metadata

The run start and stop messages are used to control the file writer, i.e. a run start message will contain enough information to start writing the subsequent detector data and metadata to a file, and the run stop message marks the end of this file.

Detector data may be events or histograms, ideally the writer should be able to handle both (although the ability to handle both simultaneously is not required).
Current files are typically histograms.

This task should be broken down into two stages:

- [x] taking an existing file, write functions to build an equivalent NeXus file
- [x] receiving data from Kafka to put into files

See:

- [hdf5](https://docs.rs/hdf5/latest/hdf5/) is the Rust crate to use for writing HDF5 files.
- https://www.nexusformat.org/

**Comment by Modularius** [comment]
Run start/stop and Detector data messages are now able to be processed, metadata messages are currently in progress.
